"use client";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Provider } from "react-redux";
import { store } from "@/store/store";
import Footer from "@/components/Footer";
import Head from "next/head"; // Import Head from next/head
import Script from 'next/script';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Add your Google site verification meta tag here */}
        <meta name="google-site-verification" content="ca-pub-5103620059122816" />
        <title>Blog for everyOne</title>
        <meta name="description" content="Description of your website" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5103620059122816"
          crossOrigin="anonymous"
        />
        <Provider store={store}>
          <Navbar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}